services:
  - type: web
    name: punch-clock-api
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: COUCHBASE_CONNSTR
        sync: false
      - key: COUCHBASE_USERNAME
        sync: false
      - key: COUCHBASE_PASSWORD
        sync: false
      - key: COUCHBASE_BUCKET
        sync: false
